### ISSUE TITLE
List Installed Packages (Apps)

### ISSUE THREAD

**Issue by joelbyler** [cheezy/ADB#3]
Would be nice to have a helper method to wrap the following shell command.

adb shell pm list packages -f

currently this can be done with the shell method, but could be wrapped to provide easier use.

**Comment by joelbyler** [comment]
Reference material on the package manager:
http://developer.android.com/tools/help/adb.html#pm

**Comment by cheezy** [comment]
@joelbyler what priority is this feature?

**Comment by joelbyler** [comment]
Its low, but I don't think it would be difficult to do.  I will try and fit this in for the coming week.

**Comment by joelbyler** [comment]
This is in ADB v 0.5.6

**Comment by leviwilson** [comment]
@joelbyler Where is the code for this? The current version in the repo says 0.5.5.

**Comment by joelbyler** [comment]
It's probly in my own repo, I must have forgotten to push upstream. I'm
away from the house for a few days but will get it on tuesday
